### ISSUE TITLE
User can set a goal for the number of fruits and vegetables they want to consume that day

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/fruit-and-veg-goals#1]
## 💰 Motivation

Users will want to set goals for fruit and vegetable consumption for the day.

## 📐 Plan

Create a form that allows users to select the desired numbers from the corresponding dropdown menus.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/108805878-f864f280-7554-11eb-97cb-e37ea31a24d3.png)

## ✅ Task List

- [x] Add a container `div` to the `body` of the HTML skeleton
- [x] Add a `div` with the class "row" and add CSS styling for it in `layout.css`
- [x] Create the header and add the app name
- [x] Create the footer and add logos from Font Awesome
- [x] Add a `form` element to the home page that includes the page's text and dropdown inputs
- [x] Listen for `submit` events on the "Next" button
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors

**Comment by angelsleung** [comment]
## 💰 Motivation

Users will want to set goals for fruit and vegetable consumption for the day.

## 📐 Plan

Create a form that allows users to select the desired numbers from the corresponding dropdown menus.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/108805878-f864f280-7554-11eb-97cb-e37ea31a24d3.png)

## ✅ Task List

- [ ] Add an HTML skeleton to `index.html` and add a container `div` to the `body`
- [ ] Create the header and add the app name
- [ ] Create the footer and add logos from Font Awesome
- [ ] Add a `form` element to the home page that includes the text and dropdown inputs
- [ ] Test all functionality again in a private browsing session
- [ ] Fix all errors
