### ISSUE TITLE
Polish website

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/fruit-and-veg-goals#17]
## ✅ Task List

- [x] Import fonts from Google Fonts and update text to match Figma
- [x] Add border-radius to buttons and inputs
- [x] Add text labels beneath the site navigation icons so it's easier for the user to tell where they go
- [x] Prevent the user from performing an empty search
- [x] If the item being searched does not exist (the API produces a `400 Bad Request`), let the user know that instead of saying it's a connection issue
- [x] On the food item page, give the user the ability to add more than one of a fruit or veggie at a time
