### ISSUE TITLE
User can search for a fruit/vegetable

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/fruit-and-veg-goals#2]
## 💰 Motivation

Users will want to look up a fruit or vegetable so that they can add it to their daily log.

## 📐 Plan

Create a form that allows users to search for a fruit or vegetable in the database.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/108923146-27c73e00-75ed-11eb-9302-06e3f70001eb.png)

## ✅ Task List

- [x] Create a view for the "Search Page" and create a "hidden" class that hides the "Home Page" view
- [x] Add a form element that includes a text input element and a submit button
- [x] Listen for `input` events on the text input element
- [x] Create a new `XMLHttpRequest()` that `GET`s the query results for the input
- [x] Create four `div` elements to display the first four results retrieved from the database
- [x] Write a function to conditionally display the images and text of the query results upon user input
- [x] Listen for `submit` events on the search button
- [x] Ensure that the result is highlighted when the user hovers over it
- [x] Listen for `click` events on the results (if they are shown to the user)
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors

**Comment by angelsleung** [comment]
## 💰 Motivation

Users will want to set goals for fruit and vegetable consumption for the day.

## 📐 Plan

Create a form that allows users to select the desired numbers from the corresponding dropdown menus.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/108805878-f864f280-7554-11eb-97cb-e37ea31a24d3.png)

## ✅ Task List

- [ ] Hi
- [ ] Hi
- [ ] 
- [x] Add a container `div` to the `body` of the HTML skeleton
- [x] Add a `div` with the class "row" and add CSS styling for it in `layout.css`
- [x] Create the header and add the app name
- [x] Create the footer and add logos from Font Awesome
- [x] Add a `form` element to the home page that includes the page's text and dropdown inputs
- [x] Listen for `submit` events on the "Next" button
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
