### ISSUE TITLE
User can view the search results

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/fruit-and-veg-goals#3]
## 💰 Motivation

Users will want to see the results of their search query.

## 📐 Plan

Create a result list that displays the top 6 matching items and provides the option to add the item to the user's daily log.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/109056761-b7282c00-7695-11eb-9311-1256f2ce279e.png)

## ✅ Task List

- [x] Create a view for the "Search Results Page" and add the "hidden" class to the other views to optionally toggle them
- [x] Create two example `div` elements that will contain the search results
- [x] Create a function that renders DOM elements containing each searched item with the data stored in `data.results`
- [x] Append the created DOM elements to the page once it is loaded
- [x] Listen for `click` events on each fruit or vegetable icon and store the information in the `data` variable
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
