### ISSUE TITLE
User can view item details

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/fruit-and-veg-goals#4]
## 💰 Motivation

Users will want to view the nutrition facts for the item they have searched and have the option to add the item to their daily log.

## 📐 Plan

Create a view for the item details that displays the nutrition facts and allows the user to add the item to their daily log of fruits or vegetables. Enable the user to reach this view by clicking on the item in the search results.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/109203923-9923ff80-7759-11eb-9942-8ced222045a3.png)

## ✅ Task List

- [x] Create a view for the item details and allow it to be toggled between hidden and visible with `display: none`
- [x] Write the HTML to set the layout of the page and add the table that will contain the nutrition facts
- [x] Add and style the buttons to add the item to the user's daily log
- [x] Store the selected item into the `data` variable and submit a `POST` query to request the nutrition information
- [x] Test to make sure that the nutrition information is being displayed properly in the table once it is loaded
- [x] Listen for `click` events on the item on both the search auto-suggestions and search results page
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
