### ISSUE TITLE
User can view their daily log

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/fruit-and-veg-goals#5]
## 💰 Motivation

Users will want to view the items they have added to their daily log.

## 📐 Plan

Create a view for the food log that lists all the items added by the user.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/109271581-93afcf00-77c4-11eb-9476-be18712d9f9a.png)

## ✅ Task List

- [x] Create another view that can be hidden or shown by optionally applying the class with `display: none`
- [x] Add a `div` to the page that will hold the daily log entries and add a few `div` examples log entries
- [x] Write a function that generates a log entry based on the information stored in the `data` variable
- [x] Write a loop that renders all entries from the data stored in the daily log and appends them to the page
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
