### ISSUE TITLE
User can view their progress toward their daily goal

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/fruit-and-veg-goals#6]
## 💰 Motivation

Users will want to view the number of fruits and vegetables they have logged and the number they still have to consume to reach their goal.

## 📐 Plan

Create a view that shows two progress bars indicating the status of fruit consumption and vegetable consumption.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/65578254/109366368-22196480-7848-11eb-9581-3915e15b38b9.png)

## ✅ Task List

- [x] Create another view that can be hidden or shown by optionally applying the class with `display: none`
- [x] Store the fruit and veggie goal number into the `data` variable
- [x] Nest two `div` elements which will form a bar chart indicating the completed number out of the total number
- [x] Add markers to both bar charts that reflect the completed amounts and amounts remaining
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
